/*  Warning - this file is automatically generated - do NOT edit  */
/*
 Created by convert_cpp_cmd2defines with the following command line arguments:
 Adjoint version -bAD_CONFIG_H -DALLOW_ADJOINT_RUN -UALLOW_TANGENTLINEAR_RUN
*/

/*  Adjoint version  */
#ifndef AD_CONFIG_H
#define AD_CONFIG_H
#define ALLOW_ADJOINT_RUN
#undef  ALLOW_TANGENTLINEAR_RUN
#endif /* AD_CONFIG_H */
