C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 20 Jun 2024 17:41
C
C  Differentiation of exch_xyz_rl in reverse (adjoint) mode:
C   gradient     of useful results: phi
C   with respect to varying inputs: phi
C
C
C
C
C
C
C
C
C
C
C
C
C
C
C
C
C
C
CBOP
C     !ROUTINE: CPP_EEOPTIONS.h
C     !INTERFACE:
C     include "CPP_EEOPTIONS.h"
C
C     !DESCRIPTION:
C     *==========================================================*
C     | CPP\_EEOPTIONS.h                                         |
C     *==========================================================*
C     | C preprocessor "execution environment" supporting        |
C     | flags. Use this file to set flags controlling the        |
C     | execution environment in which a model runs - as opposed |
C     | to the dynamical problem the model solves.               |
C     | Note: Many options are implemented with both compile time|
C     |       and run-time switches. This allows options to be   |
C     |       removed altogether, made optional at run-time or   |
C     |       to be permanently enabled. This convention helps   |
C     |       with the data-dependence analysis performed by the |
C     |       adjoint model compiler. This data dependency       |
C     |       analysis can be upset by runtime switches that it  |
C     |       is unable to recoginise as being fixed for the     |
C     |       duration of an integration.                        |
C     |       A reasonable way to use these flags is to          |
C     |       set all options as selectable at runtime but then  |
C     |       once an experimental configuration has been        |
C     |       identified, rebuild the code with the appropriate  |
C     |       options set at compile time.                       |
C     *==========================================================*
CEOP
C
C     In general the following convention applies:
C     ALLOW  - indicates an feature will be included but it may
C     CAN      have a run-time flag to allow it to be switched
C              on and off.
C              If ALLOW or CAN directives are "undef'd" this generally
C              means that the feature will not be available i.e. it
C              will not be included in the compiled code and so no
C              run-time option to use the feature will be available.
C
C     ALWAYS - indicates the choice will be fixed at compile time
C              so no run-time option will be present
C
C=== Macro related options ===
C--   Control storage of floating point operands
C     On many systems it improves performance only to use
C     8-byte precision for time stepped variables.
C     Constant in time terms ( geometric factors etc.. )
C     can use 4-byte precision, reducing memory utilisation and
C     boosting performance because of a smaller working set size.
C     However, on vector CRAY systems this degrades performance.
C     Enable to switch REAL4_IS_SLOW from genmake2 (with LET_RS_BE_REAL4):
C
C--   Control use of "double" precision constants.
C     Use D0 where it means REAL*8 but not where it means REAL*16
C
C=== IO related options ===
C--   Flag used to indicate whether Fortran formatted write
C     and read are threadsafe. On SGI the routines can be thread
C     safe, on Sun it is not possible - if you are unsure then
C     undef this option.
C
C--   Flag used to indicate whether Binary write to Local file (i.e.,
C     a different file for each tile) and read are thread-safe.
C
C--   Flag to turn off the writing of error message to ioUnit zero
C
C--   Flag to turn on old default of opening scratch files with the
C     STATUS='SCRATCH' option. This method, while perfectly FORTRAN-standard,
C     caused filename conflicts on some multi-node/multi-processor platforms
C     in the past and has been replace by something (hopefully) more robust.
C
C--   Flag defined for eeboot_minimal.F, eeset_parms.F and open_copy_data_file.F
C     to write STDOUT, STDERR and scratch files from process 0 only.
C WARNING: to use only when absolutely confident that the setup is working
C     since any message (error/warning/print) from any proc <> 0 will be lost.
C
C=== MPI, EXCH and GLOBAL_SUM related options ===
C--   Flag turns off MPI_SEND ready_to_receive polling in the
C     gather_* subroutines to speed up integrations.
C
C--   Control MPI based parallel processing
CXXX We no longer select the use of MPI via this file (CPP_EEOPTIONS.h)
CXXX To use MPI, use an appropriate genmake2 options file or use
CXXX genmake2 -mpi .
CXXX #undef  ALLOW_USE_MPI
C
C--   Control use of communication that might overlap computation.
C     Under MPI selects/deselects "non-blocking" sends and receives.
C--   Control use of communication that is atomic to computation.
C     Under MPI selects/deselects "blocking" sends and receives.
C
C--   Control XY periodicity in processor to grid mappings
C     Note: Model code does not need to know whether a domain is
C           periodic because it has overlap regions for every box.
C           Model assume that these values have been
C           filled in some way.
C
C--   disconnect tiles (no exchange between tiles, just fill-in edges
C     assuming locally periodic subdomain)
C
C--   Always cumulate tile local-sum in the same order by applying MPI allreduce
C     to array of tiles ; can get slower with large number of tiles (big set-up)
C
C--   Alternative way of doing global sum without MPI allreduce call
C     but instead, explicit MPI send & recv calls. Expected to be slower.
C
C--   Alternative way of doing global sum on a single CPU
C     to eliminate tiling-dependent roundoff errors. Note: This is slow.
C
C=== Other options (to add/remove pieces of code) ===
C--   Flag to turn on checking for errors from all threads and procs
C     (calling S/R STOP_IF_ERROR) before stopping.
C
C--   Control use of communication with other component:
C     allow to import and export from/to Coupler interface.
C
C--   Activate some pieces of code for coupling to GEOS AGCM
C
C=== And define Macros ===
CBOP
C     !ROUTINE: CPP_EEMACROS.h
C     !INTERFACE:
C     include "CPP_EEMACROS.h"
C     !DESCRIPTION:
C     *==========================================================*
C     | CPP_EEMACROS.h
C     *==========================================================*
C     | C preprocessor "execution environment" supporting
C     | macros. Use this file to define macros for  simplifying
C     | execution environment in which a model runs - as opposed
C     | to the dynamical problem the model solves.
C     *==========================================================*
CEOP
C
C
C     In general the following convention applies:
C     ALLOW  - indicates an feature will be included but it may
C     CAN      have a run-time flag to allow it to be switched
C              on and off.
C              If ALLOW or CAN directives are "undef'd" this generally
C              means that the feature will not be available i.e. it
C              will not be included in the compiled code and so no
C              run-time option to use the feature will be available.
C
C     ALWAYS - indicates the choice will be fixed at compile time
C              so no run-time option will be present
C
C     Flag used to indicate which flavour of multi-threading
C     compiler directives to use. Only set one of these.
C     USE_SOLARIS_THREADING  - Takes directives for SUN Workshop
C                              compiler.
C     USE_KAP_THREADING      - Takes directives for Kuck and
C                              Associates multi-threading compiler
C                              ( used on Digital platforms ).
C     USE_IRIX_THREADING     - Takes directives for SGI MIPS
C                              Pro Fortran compiler.
C     USE_EXEMPLAR_THREADING - Takes directives for HP SPP series
C                              compiler.
C     USE_C90_THREADING      - Takes directives for CRAY/SGI C90
C                              system F90 compiler.
C
C
C
C
C
C
C--   Define the mapping for the _BARRIER macro
C     On some systems low-level hardware support can be accessed through
C     compiler directives here.
C
C--   Define the mapping for the BEGIN_CRIT() and  END_CRIT() macros.
C     On some systems we simply execute this section only using the
C     master thread i.e. its not really a critical section. We can
C     do this because we do not use critical sections in any critical
C     sections of our code!
C
C--   Define the mapping for the BEGIN_MASTER_SECTION() and
C     END_MASTER_SECTION() macros. These are generally implemented by
C     simply choosing a particular thread to be "the master" and have
C     it alone execute the BEGIN_MASTER..., END_MASTER.. sections.
C
CcnhDebugStarts
C      Alternate form to the above macros that increments (decrements) a counter each
C      time a MASTER section is entered (exited). This counter can then be checked in barrier
C      to try and detect calls to BARRIER within single threaded sections.
C      Using these macros requires two changes to Makefile - these changes are written
C      below.
C      1 - add a filter to the CPP command to kill off commented _MASTER lines
C      2 - add a filter to the CPP output the converts the string N EWLINE to an actual newline.
C      The N EWLINE needs to be changes to have no space when this macro and Makefile changes
C      are used. Its in here with a space to stop it getting parsed by the CPP stage in these
C      comments.
C      #define IF ( a .EQ. 1 ) THEN  IF ( a .EQ. 1 ) THEN  N EWLINE      CALL BARRIER_MS(a)
C      #define ENDIF    CALL BARRIER_MU(a) N EWLINE        ENDIF
C      'CPP = cat $< | $(TOOLSDIR)/set64bitConst.sh |  grep -v '^[cC].*_MASTER' | cpp  -traditional -P'
C      .F.f:
C      $(CPP) $(DEFINES) $(INCLUDES) |  sed 's/N EWLINE/\n/' > $@
CcnhDebugEnds
C
C--   Control storage of floating point operands
C     On many systems it improves performance only to use
C     8-byte precision for time stepped variables.
C     Constant in time terms ( geometric factors etc.. )
C     can use 4-byte precision, reducing memory utilisation and
C     boosting performance because of a smaller working
C     set size. However, on vector CRAY systems this degrades
C     performance.
C- Note: global_sum/max macros were used to switch to  JAM routines (obsolete);
C  in addition, since only the R4 & R8 S/R are coded, GLOBAL RS & RL macros
C  enable to call the corresponding R4 or R8 S/R.
C
C
C
C- Note: a) exch macros were used to switch to  JAM routines (obsolete)
C        b) exch R4 & R8 macros are not practically used ; if needed,
C           will directly call the corrresponding S/R.
C
C--   Control use of JAM routines for Artic network (no longer supported)
C     These invoke optimized versions of "exchange" and "sum" that
C     utilize the programmable aspect of Artic cards.
CXXX No longer supported ; started to remove JAM routines.
CXXX #ifdef LETS_MAKE_JAM
CXXX #define CALL GLOBAL_SUM_R8 ( a, b) CALL GLOBAL_SUM_R8_JAM ( a, b)
CXXX #define CALL GLOBAL_SUM_R8 ( a, b ) CALL GLOBAL_SUM_R8_JAM ( a, b )
CXXX #define CALL EXCH_XY_RS ( a, b ) CALL EXCH_XY_R8_JAM ( a, b )
CXXX #define CALL EXCH_XY_RL ( a, b ) CALL EXCH_XY_R8_JAM ( a, b )
CXXX #define CALL EXCH_XYZ_RS ( a, b ) CALL EXCH_XYZ_R8_JAM ( a, b )
CXXX #define CALL EXCH_XYZ_RL ( a, b ) CALL EXCH_XYZ_R8_JAM ( a, b )
CXXX #endif
C
C--   Control use of "double" precision constants.
C     Use d0 where it means REAL*8 but not where it means REAL*16
C
C--   Substitue for 1.D variables
C     Sun compilers do not use 8-byte precision for literals
C     unless .Dnn is specified. CRAY vector machines use 16-byte
C     precision when they see .Dnn which runs very slowly!
C
C--   Set the format for writing processor IDs, e.g. in S/R eeset_parms
C     and S/R open_copy_data_file. The default of I9.9 should work for
C     a long time (until we will use 10e10 processors and more)
C
C--   Set the format for writing ensemble task IDs in S/R eeset_parms
C     and S/R open_copy_data_file.
C
C--   Set ACTION= in OPEN instruction for input file (before doing IO)
C     leave it empty (if EXCLUDE_OPEN_ACTION) or set it to proper value
C
C
C
CBOP
C     !ROUTINE: EXCH_XYZ_RL
C
C     !INTERFACE:
      SUBROUTINE EXCH_XYZ_RL_B(phi, phib, mythid)
      IMPLICIT NONE
C
C     === Global data ===
CBOP
C    !ROUTINE: SIZE.h
C    !INTERFACE:
C    include SIZE.h
C    !DESCRIPTION: \bv
C     *==========================================================*
C     | SIZE.h Declare size of underlying computational grid.
C     *==========================================================*
C     | The design here supports a three-dimensional model grid
C     | with indices I,J and K. The three-dimensional domain
C     | is comprised of nPx*nSx blocks (or tiles) of size sNx
C     | along the first (left-most index) axis, nPy*nSy blocks
C     | of size sNy along the second axis and one block of size
C     | Nr along the vertical (third) axis.
C     | Blocks/tiles have overlap regions of size OLx and OLy
C     | along the dimensions that are subdivided.
C     *==========================================================*
C     \ev
C
C     Voodoo numbers controlling data layout:
C     sNx :: Number of X points in tile.
C     sNy :: Number of Y points in tile.
C     OLx :: Tile overlap extent in X.
C     OLy :: Tile overlap extent in Y.
C     nSx :: Number of tiles per process in X.
C     nSy :: Number of tiles per process in Y.
C     nPx :: Number of processes to use in X.
C     nPy :: Number of processes to use in Y.
C     Nx  :: Number of points in X for the full domain.
C     Ny  :: Number of points in Y for the full domain.
C     Nr  :: Number of points in vertical direction.
CEOP
      INTEGER snx
      INTEGER sny
      INTEGER olx
      INTEGER oly
      INTEGER nsx
      INTEGER nsy
      INTEGER npx
      INTEGER npy
      INTEGER nx
      INTEGER ny
      INTEGER nr
      PARAMETER (snx=62, sny=62, olx=4, oly=4, nsx=1, nsy=1, npx=1, npy=
     +   1, nx=snx*nsx*npx, ny=sny*nsy*npy, nr=31)
C
C     MAX_OLX :: Set to the maximum overlap region size of any array
C     MAX_OLY    that will be exchanged. Controls the sizing of exch
C                routine buffers.
      INTEGER max_olx
      INTEGER max_oly
      PARAMETER (max_olx=olx, max_oly=oly)
C
CBOP
C     !ROUTINE: EEPARAMS.h
C     !INTERFACE:
C     include "EEPARAMS.h"
C
C     !DESCRIPTION:
C     *==========================================================*
C     | EEPARAMS.h                                               |
C     *==========================================================*
C     | Parameters for "execution environemnt". These are used   |
C     | by both the particular numerical model and the execution |
C     | environment support routines.                            |
C     *==========================================================*
CEOP
C
C     ========  EESIZE.h  ========================================
C
C     MAX_LEN_MBUF  :: Default message buffer max. size
C     MAX_LEN_FNAM  :: Default file name max. size
C     MAX_LEN_PREC  :: Default rec len for reading "parameter" files
C
      INTEGER max_len_mbuf
      PARAMETER (max_len_mbuf=512)
      INTEGER max_len_fnam
      PARAMETER (max_len_fnam=512)
      INTEGER max_len_prec
      PARAMETER (max_len_prec=200)
C
C     MAX_NO_THREADS  :: Maximum number of threads allowed.
C     GSVec_size      :: Maximum buffer size for Global Sum Vector array
      INTEGER max_no_threads
      PARAMETER (max_no_threads=4)
      INTEGER gsvec_size
      PARAMETER (gsvec_size=1024)
C
C     Particularly weird and obscure voodoo numbers
C     lShare :: This wants to be the length in
C               [148]-byte words of the size of
C               the address "window" that is snooped
C               on an SMP bus. By separating elements in
C               the global sum buffer we can avoid generating
C               extraneous invalidate traffic between
C               processors. The length of this window is usually
C               a cache line i.e. small O(64 bytes).
C               The buffer arrays are usually short arrays
C               and are declared REAL ARRA(lShare[148],LBUFF).
C               Setting lShare[148] to 1 is like making these arrays
C               one dimensional.
      INTEGER cachelinesize
      INTEGER lshare1
      INTEGER lshare4
      INTEGER lshare8
      PARAMETER (cachelinesize=256)
      PARAMETER (lshare1=cachelinesize)
      PARAMETER (lshare4=cachelinesize/4)
      PARAMETER (lshare8=cachelinesize/8)
C
C     ========  EESIZE.h  ========================================
C
C     Symbolic values
C     precXXXX :: precision used for I/O
      INTEGER precfloat32
      PARAMETER (precfloat32=32)
      INTEGER precfloat64
      PARAMETER (precfloat64=64)
C
C     Real-type constant for some frequently used simple number (0,1,2,1/2):
      REAL*8 zerors, oners, twors, halfrs
      PARAMETER (zerors=0.0d0, oners=1.0d0)
      PARAMETER (twors=2.0d0, halfrs=0.5d0)
      REAL*8 zerorl, onerl, tworl, halfrl
      PARAMETER (zerorl=0.0d0, onerl=1.0d0)
      PARAMETER (tworl=2.0d0, halfrl=0.5d0)
C
C     UNSET_xxx :: Used to indicate variables that have not been given a value
      REAL*8 unset_float8
      PARAMETER (unset_float8=1.234567d5)
      REAL*4 unset_float4
      PARAMETER (unset_float4=1.234567e5)
      REAL*8 unset_rl
      PARAMETER (unset_rl=1.234567d5)
      REAL*8 unset_rs
      PARAMETER (unset_rs=1.234567d5)
      INTEGER unset_i
      PARAMETER (unset_i=123456789)
C
C     debLevX  :: used to decide when to print debug messages
      INTEGER deblevzero
      INTEGER debleva, deblevb, deblevc, deblevd, debleve
      PARAMETER (deblevzero=0)
      PARAMETER (debleva=1)
      PARAMETER (deblevb=2)
      PARAMETER (deblevc=3)
      PARAMETER (deblevd=4)
      PARAMETER (debleve=5)
C
C     SQUEEZE_RIGHT      :: Flag indicating right blank space removal
C                           from text field.
C     SQUEEZE_LEFT       :: Flag indicating left blank space removal
C                           from text field.
C     SQUEEZE_BOTH       :: Flag indicating left and right blank
C                           space removal from text field.
C     PRINT_MAP_XY       :: Flag indicating to plot map as XY slices
C     PRINT_MAP_XZ       :: Flag indicating to plot map as XZ slices
C     PRINT_MAP_YZ       :: Flag indicating to plot map as YZ slices
C     commentCharacter   :: Variable used in column 1 of parameter
C                           files to indicate comments.
C     INDEX_I            :: Variable used to select an index label
C     INDEX_J               for formatted input parameters.
C     INDEX_K
C     INDEX_NONE
      CHARACTER*(*) squeeze_right
      PARAMETER (squeeze_right='R')
      CHARACTER*(*) squeeze_left
      PARAMETER (squeeze_left='L')
      CHARACTER*(*) squeeze_both
      PARAMETER (squeeze_both='B')
      CHARACTER*(*) print_map_xy
      PARAMETER (print_map_xy='XY')
      CHARACTER*(*) print_map_xz
      PARAMETER (print_map_xz='XZ')
      CHARACTER*(*) print_map_yz
      PARAMETER (print_map_yz='YZ')
      CHARACTER*(*) commentcharacter
      PARAMETER (commentcharacter='#')
      INTEGER index_i
      INTEGER index_j
      INTEGER index_k
      INTEGER index_none
      PARAMETER (index_i=1, index_j=2, index_k=3, index_none=4)
C
C     EXCH_IGNORE_CORNERS :: Flag to select ignoring or
C     EXCH_UPDATE_CORNERS    updating of corners during an edge exchange.
      INTEGER exch_ignore_corners
      INTEGER exch_update_corners
      PARAMETER (exch_ignore_corners=0, exch_update_corners=1)
C
C     FORWARD_SIMULATION
C     REVERSE_SIMULATION
C     TANGENT_SIMULATION
      INTEGER forward_simulation
      INTEGER reverse_simulation
      INTEGER tangent_simulation
      PARAMETER (forward_simulation=0, reverse_simulation=1, 
     +   tangent_simulation=2)
C
C--   COMMON /EEPARAMS_L/ Execution environment public logical variables.
C     eeBootError    :: Flags indicating error during multi-processing
C     eeEndError     :: initialisation and termination.
C     fatalError     :: Flag used to indicate that the model is ended with an error
C     debugMode      :: controls printing of debug msg (sequence of S/R calls).
C     useSingleCpuIO :: When useSingleCpuIO is set, MDS_WRITE_FIELD outputs from
C                       master MPI process only. -- NOTE: read from main parameter
C                       file "data" and not set until call to INI_PARMS.
C     useSingleCpuInput :: When useSingleCpuInput is set, EXF_INTERP_READ
C                       reads forcing files from master MPI process only.
C                       -- NOTE: read from main parameter file "data"
C                          and defaults to useSingleCpuInput = useSingleCpuIO
C     printMapIncludesZeros  :: Flag that controls whether character constant
C                               map code ignores exact zero values.
C     useCubedSphereExchange :: use Cubed-Sphere topology domain.
C     useCoupler     :: use Coupler for a multi-components set-up.
C     useNEST_PARENT :: use Parent Nesting interface (pkg/nest_parent)
C     useNEST_CHILD  :: use Child  Nesting interface (pkg/nest_child)
C     useNest2W_parent :: use Parent 2-W Nesting interface (pkg/nest2w_parent)
C     useNest2W_child  :: use Child  2-W Nesting interface (pkg/nest2w_child)
C     useOASIS       :: use OASIS-coupler for a multi-components set-up.
      COMMON /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode
     +, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, 
     +usecubedsphereexchange, usecoupler, usenest_parent, usenest_child
     +, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, 
     +usesigreg
C    &  eeBootError, fatalError, eeEndError,
      LOGICAL eebooterror
      LOGICAL eeenderror
      LOGICAL fatalerror
      LOGICAL debugmode
      LOGICAL usesinglecpuio
      LOGICAL usesinglecpuinput
      LOGICAL printmapincludeszeros
      LOGICAL usecubedsphereexchange
      LOGICAL usecoupler
      LOGICAL usenest_parent
      LOGICAL usenest_child
      LOGICAL usenest2w_parent
      LOGICAL usenest2w_child
      LOGICAL useoasis
      LOGICAL usesetrlstk
      LOGICAL usesigreg
C
C--   COMMON /EPARAMS_I/ Execution environment public integer variables.
C     errorMessageUnit    :: Fortran IO unit for error messages
C     standardMessageUnit :: Fortran IO unit for informational messages
C     maxLengthPrt1D :: maximum length for printing (to Std-Msg-Unit) 1-D array
C     scrUnit1      :: Scratch file 1 unit number
C     scrUnit2      :: Scratch file 2 unit number
C     eeDataUnit    :: Unit # for reading "execution environment" parameter file
C     modelDataUnit :: Unit number for reading "model" parameter file.
C     numberOfProcs :: Number of processes computing in parallel
C     pidIO         :: Id of process to use for I/O.
C     myBxLo, myBxHi :: Extents of domain in blocks in X and Y
C     myByLo, myByHi :: that each threads is responsble for.
C     myProcId      :: My own "process" id.
C     myPx          :: My X coord on the proc. grid.
C     myPy          :: My Y coord on the proc. grid.
C     myXGlobalLo   :: My bottom-left (south-west) x-index global domain.
C                      The x-coordinate of this point in for example m or
C                      degrees is *not* specified here. A model needs to
C                      provide a mechanism for deducing that information
C                      if it is needed.
C     myYGlobalLo   :: My bottom-left (south-west) y-index in global domain.
C                      The y-coordinate of this point in for example m or
C                      degrees is *not* specified here. A model needs to
C                      provide a mechanism for deducing that information
C                      if it is needed.
C     nThreads      :: No. of threads
C     nTx, nTy      :: No. of threads in X and in Y
C                      This assumes a simple cartesian gridding of the threads
C                      which is not required elsewhere but that makes it easier
C     ioErrorCount  :: IO Error Counter. Set to zero initially and increased
C                      by one every time an IO error occurs.
      COMMON /eeparams_i/ errormessageunit, standardmessageunit, 
     +maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     +numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, 
     +myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     +ioerrorcount
      INTEGER errormessageunit
      INTEGER standardmessageunit
      INTEGER maxlengthprt1d
      INTEGER scrunit1
      INTEGER scrunit2
      INTEGER eedataunit
      INTEGER modeldataunit
      INTEGER ioerrorcount(max_no_threads)
      INTEGER mybxlo(max_no_threads)
      INTEGER mybxhi(max_no_threads)
      INTEGER mybylo(max_no_threads)
      INTEGER mybyhi(max_no_threads)
      INTEGER myprocid
      INTEGER mypx
      INTEGER mypy
      INTEGER myxgloballo
      INTEGER myygloballo
      INTEGER nthreads
      INTEGER ntx
      INTEGER nty
      INTEGER numberofprocs
      INTEGER pidio
C
C---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
C
C     !INPUT/OUTPUT PARAMETERS:
C     === Routine arguments ===
C     phi    :: Array with overlap regions are to be exchanged
C     myThid :: My thread id.
      REAL*8 phi(1-olx:snx+olx, 1-oly:sny+oly, nr, nsx, nsy)
      REAL*8 phib(1-olx:snx+olx, 1-oly:sny+oly, nr, nsx, nsy)
      INTEGER mythid
C
C     !LOCAL VARIABLES:
C     == Local variables ==
C     OL[wens]       :: Overlap extents in west, east, north, south.
C     exchWidth[XY]  :: Extent of regions that will be exchanged.
      INTEGER olw, ole, oln, ols, exchwidthx, exchwidthy, mynz
      EXTERNAL EXCH1_RL_CUBE
      EXTERNAL EXCH1_RL_CUBE_B
      EXTERNAL EXCH1_RL
      EXTERNAL EXCH1_RL_B
CEOP
C
C
      olw = olx
      ole = olx
      oln = oly
      ols = oly
      exchwidthx = olx
      exchwidthy = oly
      mynz = nr
      IF (usecubedsphereexchange) THEN
        CALL EXCH1_RL_CUBE_B(phi, phib, .false., olw, ole, ols, oln, 
     +                       mynz, exchwidthx, exchwidthy, 
     +                       exch_update_corners, mythid)
      ELSE
        CALL EXCH1_RL_B(phi, phib, olw, ole, ols, oln, mynz, exchwidthx
     +                  , exchwidthy, exch_update_corners, mythid)
      END IF
      END

